const books = [
        { title: "DISCIPLINE = FREEDOM", cover: "ebooks/images/discipline=free.PNG", pdf: "ebooks/discipline=free.pdf" },
        { title: "THE 48 LAWS OF POWER", cover: "ebooks/images/48lawofpower.jpg", pdf: "ebooks/48lawsofpower.pdf" },
        { title: "THE ART OF SEDUCTION-robert greene", cover: "ebooks/images/artofseduction.PNG", pdf: "ebooks/artofseduction.pdf" },
        { title: "osho's THE BOOK OF SECRETS", cover: "ebooks/images/bookofsecrets.jpg", pdf: "ebooks/bookofsecrets.pdf" },
        { title: "agarwal's Q/A", cover: "ebooks/images/agarwalqa.PNG", pdf: "ebooks/agarwalqa.pdf" },
        { title: "PYTHON COOKBOOK", cover: "ebooks/images/pycookbook.PNG", pdf: "ebooks/pycookbook.pdf" },
        { title: "GUIDE TO SWING TRADING", cover: "ebooks/images/swingtrade.PNG", pdf: "ebooks/swingtrade.pdf" },
        { title: "FOREX FOR BEGINNERS", cover: "ebooks/images/forex.PNG", pdf: "ebooks/forex.pdf" },
        { title: "CONSTRUCTING THE BEST TRADING STRATERGY", cover: "ebooks/images/default.jpg", pdf: "ebooks/strattrade.pdf" },
        { title: "CANDLESTICKS", cover: "ebooks/images/candlesticks.PNG", pdf: "ebooks/candlesticks.pdf" },
        { title: "4 HOUR WORK WEEK", cover: "ebooks/images/4hourworkweek.jpg", pdf: "ebooks/4hourworkweek.pdf" },
        { title: "7 HABITS  OF HIGHLY EFFECTIVE PEOPLE", cover: "ebooks/images/7hofhepeople.jpg", pdf: "ebooks/7hofhepeople.pdf" },
        { title: "12 RULES FOR LIFE", cover: "ebooks/images/12-Rules-for-Life.jpg", pdf: "ebooks/12-Rules-for-Life.pdf" },
        { title: "ZERO TO ONE", cover: "ebooks/images/1.jpg", pdf: "ebooks/021.pdf" },
        { title: "ACHIEVEMENT HABIT", cover: "ebooks/images/2.jpg", pdf: "ebooks/achivement-habit.pdf" },
        { title: "ATOMIC HABITS", cover: "ebooks/images/3.jpg", pdf: "ebooks/Atomic_Habits.pdf" },
        { title: "WHY 'A'GRADE WORKS FOR 'C'GRADE", cover: "ebooks/images/4.jpg", pdf: "ebooks/Why_AC.pdf" },
        { title: "CANT HURT ME", cover: "ebooks/images/5.jpg", pdf: "ebooks/cant-hurt-me.pdf" },
        { title: "RICH DAD POOR DAD", cover: "ebooks/images/6.jpg", pdf: "ebooks/rdpd.pdf" },
        { title: "RICHDAD'S CASHFLOW QUADRENT", cover: "ebooks/images/7.jpg", pdf: "ebooks/cashflow1.pdf" },
        { title: "CRUCIAL CONVERSATIONS", cover: "ebooks/images/8.jpg", pdf: "ebooks/cc.pdf" },
        { title: "FOCUS", cover: "ebooks/images/9.jpg", pdf: "ebooks/focus.pdf" },
        { title: "DEEPWORK", cover: "ebooks/images/10.jpg", pdf: "ebooks/deepwork.pdf" },
        { title: "DO IT TODAY", cover: "ebooks/images/11.jpg", pdf: "ebooks/doittoday.pdf" },
        { title: "DOTCOM SECRETS", cover: "ebooks/images/12.jpg", pdf: "ebooks/dotcomsecrets.pdf" },
        { title: "EAT THAT FROG", cover: "ebooks/images/13.jpg", pdf: "ebooks/eatfrog.pdf" },
        { title: "EGO IS THE ENEMY", cover: "ebooks/images/14.jpg", pdf: "ebooks/egoenemy.pdf" },
        { title: "ESSENTIALISM", cover: "ebooks/images/15.jpg", pdf: "ebooks/essentialism.pdf" },
        { title: "FINISH WHAT YOU START", cover: "ebooks/images/16.jpg", pdf: "ebooks/book/finishwustart.pdf" },
        { title: "GAMES PEOPLE PLAY", cover: "ebooks/images/17.jpg", pdf: "ebooks/gppm.pdf" },
        { title: "HOW TO TALK TO ANYONE", cover: "ebooks/images/18.jpg", pdf: "ebooks/htta.pdf" },
        { title: "HOW TO WIN FRIENDS AND INFLUENCE PEOPLE", cover: "ebooks/images/19.jpg", pdf: "ebooks/win&influence.pdf" },
        { title: "IKIGAI", cover: "ebooks/images/20.jpg", pdf: "ebooks/Ikigai.pdf" },
        { title: "TO KILL A MOCKING BIRD", cover: "ebooks/images/21.jpg", pdf: "ebooks/killamockingbird.pdf" },
        { title: "MONEY MASTERS THE GAME", cover: "ebooks/images/22.jpg", pdf: "ebooks/mmtg.pdf" },
        { title: "RICHDAD'S RETIRE YOUNG RETIRE RICH", cover: "ebooks/images/23.jpg", pdf: "ebooks/ryrr.pdf" },
        { title: "REWORK", cover: "ebooks/images/24.jpg", pdf: "ebooks/rework.pdf" },
        { title: "RISING STRONG", cover: "ebooks/images/25.jpg", pdf: "ebooks/risingstrong.pdf" },
        { title: "SPY THE LIE", cover: "ebooks/images/26.jpg", pdf: "ebooks/spythelie.pdf" },
        { title: "STOP WORRYING START LIVING", cover: "ebooks/images/27.jpg", pdf: "ebooks/swsl.pdf" },
        { title: "CORPORATE CHANAKYA", cover: "ebooks/images/cc.jpg", pdf: "ebooks/cc.pdf" },
        { title: "SURROUNDED BY IDIOTS", cover: "ebooks/images/28.jpg", pdf: "ebooks/sbidts.pdf" },
        { title: " THE $1OO STARTUP", cover: "ebooks/images/29.jpg", pdf: "ebooks/$100.pdf" },
        { title: "THE ART OF WAR", cover: "ebooks/images/30.jpg", pdf: "ebooks/artofwar.pdf" },
        { title: "THE COMPOUND EFFECT", cover: "ebooks/images/31.jpg", pdf: "ebooks/tce.pdf" },
        { title: "THE E-MYTH REVISITED", cover: "ebooks/images/32.jpg", pdf: "ebooks/emyth.pdf" },
        { title: "THE MIRACLE MORNING", cover: "ebooks/images/33.jpg", pdf: "ebooks/mirmor.pdf" },
        { title: "THE SUBTLE ART OF NOT GIVING A F***", cover: "ebooks/images/34.jpg", pdf: "ebooks/tsangf.pdf" },
        { title: "THE WAY OF SUPERIOR MAN", cover: "ebooks/images/35.jpg", pdf: "ebooks/sman.pdf" },
        { title: "THE 80/20 PRINCIPLE", cover: "ebooks/images/36.jpg", pdf: "ebooks/8020.pdf" },
        { title: "THE MILLIONARE FASTLANE", cover: "ebooks/images/37.jpg", pdf: "ebooks/fastlane.pdf" },
        { title: "CHANAKYA ON DAILY LIFE", cover: "ebooks/images/cdaily.jpg", pdf: "ebooks/cdaily.pdf" },
        { title: "THE BROTHER KARAMAZO", cover: "ebooks/images/brokar.jpg", pdf: "ebooks/brokar.pdf" },
        { title: "THE ONE THING", cover: "ebooks/images/38.jpg", pdf: "ebooks/onething.pdf" },
        { title: "THE PSYCHOLOGY OF MONEY", cover: "ebooks/images/39.jpg", pdf: "ebooks/psymoney.pdf" },
        { title: "CRIME AND PUNISHMENT", cover: "ebooks/images/candp.jpg", pdf: "ebooks/candp.pdf" },
        { title: "THE RICHEST MAN IN BABYLON", cover: "ebooks/images/40.jpg", pdf: "ebooks/trmib.pdf" },
        { title: "THINK AND GROW RICH", cover: "ebooks/images/41.jpg", pdf: "ebooks/tagr.pdf" },
        { title: "TRANSFORM YOUR HABITS", cover: "ebooks/images/42.jpg", pdf: "ebooks/tyh.pdf" },
        { title: "TRIBE OF MENTORS", cover: "ebooks/images/43.jpg", pdf: "ebooks/tom.pdf" }

      ];
