const quotes=[
"48.Never Outshine the Master",
"48.Never Put Too Much Trust in Friends; Learn How to Use Enemies",
"48.Conceal Your Intentions",
"48.Always Say Less Than Necessary",
"48.So Much Depends on Reputation; Guard It with Your Life",
"48.Court Attention at All Costs",
"48.Get Others to Do the Work for You, but Always Take the Credit",
"48.Make Other People Come to You - Use Bait If Necessary",
"48.Win Through Your Actions, Never Through Argument",
"48.Infection: Avoid the Unhappy and Unlucky",
"48.Learn to Keep People Dependent on You",
"48.Use Selective Honesty and Generosity to Disarm Your Victim",
"48.When Asking for Help, Appeal to People's Self-Interest, Never to Their Mercy or Gratitude",
"48.Pose as a Friend, Work as a Spy",
"48.Crush Your Enemy Totally",
"48.Use Absence to Increase Respect and Honor",
"48.Keep Others in Suspended Terror: Cultivate an Air of Unpredictability",
"48.Do Not Build Fortresses to Protect Yourself - Isolation Is Dangerous",
"48.Know Who You're Dealing With - Do Not Offend the Wrong Person",
"48.Do Not Commit to Anyone",
"48.Play a Sucker to Catch a Sucker - Seem Dumber Than Your Mark",
"48.Use the Surrender Tactic: Transform Weakness into Power",
"48.Concentrate Your Forces",
"48.Play the Perfect Courtier",
"48.Re-Create Yourself",
"48.Keep Your Hands Clean",
"48.Play on People's Need to Believe to Create a Cultlike Following",
"48.Enter Action with Boldness",
"48.Plan All the Way to the End",
"48.Make Your Accomplishments Seem Effortless",
"48.Control the Options: Get Others to Play with the Cards You Deal",
"48.Play to People's Fantasies",
"48.Discover Each Man's Thumbscrew",
"48.Be Royal in Your Own Fashion: Act Like a King to Be Treated Like One",
"48.Master the Art of Timing",
"48.Disdain Things You Cannot Have: Ignoring Them Is the Best Revenge",
"48.Create Compelling Spectacles",
"48.Think as You Like, but Behave Like Others",
"48.Stir up Waters to Catch Fish",
"48.Despise the Free Lunch",
"48.Avoid Stepping into a Great Man's Shoes",
"48.Strike the Shepherd and the Sheep Will Scatter",
"48.work on the Hearts and Minds of Others",
"48.Disarm and Infuriate with the Mirror Effect",
"48.Preach the Need for Change, but Never Reform Too Much at Once",
"48.Never Appear Too Perfect",
"48.Do Not Go Past the Mark You Aimed For; In Victory, Know When to Stop",
"48.Assume Formlessness",
"(not infinite) Work expands to fill time available for completion",
"(not infinite) Time expand or shrink according to your mood",
"(not infinite) work only with professionals and don't do the work of your co-workers",
"(not infinite) if you find yourself wasting time, identify whats demotivated you",
"(not infinite) Have a clear goal in mind",
"(not infinite) Establish a holy hour for planning",
"(not infinite) don't put rountine works before tasks that will take you forward",
"(not infinite) start the sole project of life now, once you start things will start happening",
"(confidence) small wins Lead to universities in space",
"(confidence) easy success isn't as powerful as blood,sweat, and tear success",
"(confidence) if you feel extremly uncomfortable with failure, try rejection therapy",
"(confidence) the behaviour of your friend's influence your own",
"(confidence) Avoid negativity, it's stronger than positivity",
"(confidence) you don't need other's to encourage yourself",
"(confidence) For maximum results,Find a mentor",
"(confidence) Break goals into smaller pieces and simplify",
"(confidence) Focus on the big picture",
"(HTB disciplined) discipline is a process, not a destination",
"(sucess habits) dressing well have a powerful psychological effect how you feel  ",
"(dis=free)Fight weak emotions with the power of logic; fight the weakness of logic with the power of emotion."
];
